force-app/main/default/objects/Account/fields/Estimated_Country__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Country__c</fullName>
    <label>Estimated Country</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Tax_Code__c</fullName>
    <externalId>true</externalId>
    <label>Tax Code</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GlobalSearchController.cls
public class GlobalSearchController {

    public static List<List<sObject>> searchBankRecords(String searchKey) {
        
        if (String.isBlank(searchKey) || searchKey.length() < 3) {
            return new List<List<sObject>>();
        }
        
        List<List<sObject>> searchResults = [
            FIND :searchKey IN ALL FIELDS
            RETURNING 
                Lead(Name, Email, Status),
                Account(Name, Tax_Code__c, Estimated_Country__c)
        ];
        
        return searchResults;
    }
}